baseURL = "https://www.apm.best/" 
languageCode = "zh-CN"
title = "每天4小时"
theme = "ananke"

# 自动检测是否包含中文/日文/韩文，该参数会影响摘要和字数统计功能，建议设置为true
hasCJKLanguage = true

# 若为 false，`Getting Started` 这样的英文标签将会被转换为 `getting-started`
preserveTaxonomyNames = true

# 分页
paginate = 10
paginatePath = "page"

# 启用 Emoji; see emoji-cheat-sheet.com
enableEmoji = false

# 创建robots.txt，建议设置为true
enableRobotsTXT = false

# 定义文章访问路径，详细见下文"URL管理" See "content-management/urls/"
# permalinks = ""

[params]
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  featured_image = "/images/beach.jpg"
  recent_posts_number = 5
