title = "每天4小时"
baseURL = "https://www.apm.best/" 
languageCode = "zh-CN"
theme = "ananke"

# 自动检测是否包含中文/日文/韩文，该参数会影响摘要和字数统计功能，建议设置为true
hasCJKLanguage = true

# 若为 false，`Getting Started` 这样的英文标签将会被转换为 `getting-started`
preserveTaxonomyNames = true

# 分页
paginate = 10
paginatePath = "page"

googleAnalytics = ""

# 启用 Emoji; see emoji-cheat-sheet.com
enableEmoji = false

# 创建robots.txt，建议设置为true
enableRobotsTXT = true

# 定义文章访问路径，详细见下文"URL管理" See "content-management/urls/"
# permalinks = ""

# disqusShortname = "apm-best"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "分享互联网产品技术、广告投放优化策略、Afflimate Marketing、智能家居等"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/makefeics"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  featured_image = "/images/beach.jpg"
  recent_posts_number = 8
  commentoEnable = false
  show_reading_time = true

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
# 参数配置项参考：https://valine.js.org/configuration.html
[params.valine]
  enable = true
  appId = 'jLMpCSVDrCKbffKdEwazLJjp-gzGzoHsz'
  appKey = 'eoFP9hmyVxPrjOhUDhvO42ip'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mp' # 头像配置：https://valine.js.org/avatar.html
  placeholder = '✒️说点什么吧，该评论支持Markdown语法，请文明留言哦...'
  visitor = true # 阅读量统计配置：https://valine.js.org/visitor.html
